# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

#---------------------------------#
#      General Configuration      #
#---------------------------------#

# Build version format
version: "{build}"

# What combinations to test
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"

# Caches the directory containing all installed npm modules
cache:
  - node_modules

branches:
  only:
    - master

#---------------------------------#
#           Installation          #
#---------------------------------#

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # Install latest version of npm
  - npm install npm@latest -g
  # Install node-gyp
  - npm install -g node-gyp
  # Install modules
  - npm install

build: off

#---------------------------------#
#              Tests              #
#---------------------------------#

test_script:
  - npm test

#---------------------------------#
#            Post-build           #
#---------------------------------#

# on_success:
#   - ps: Invoke-RestMethod https://raw.githubusercontent.com/DS-Development/delet/master/ci/appveyor/send.ps1 -o send.ps1
#   - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DS-Development/delet/master/ci/appveyor/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
